---
abstract: 'to_yaml() method for all objects.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UNIVERSAL-to_yaml
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Best: 0
  YAML::Syck: 0.45
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.10'
