abstract: to_yaml() method for all objects.
author: Kang-min Liu  C<< <gugod@gugod.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: UNIVERSAL-to_yaml
no_index: 
  directory: 
    - inc
    - t
requires: 
  Best: 0
  YAML::Syck: 0.45
  perl: 5.8.0
version: 0.10
